const COINS=[['BTC','Bitcoin'],['ETH','Ethereum'],['USDT','Tether'],['SOL','Solana'],['BNB','BNB'],['XRP','XRP'],['USDC','USD Coin'],['ADA','Cardano'],['DOGE','Dogecoin'],['SHIB','Shiba Inu'],['AVAX','Avalanche'],['TON','Toncoin'],['TRX','TRON'],['LINK','Chainlink'],['DOT','Polkadot'],['POL','Polygon'],['NEAR','Near Protocol'],['LTC','Litecoin'],['UNI','Uniswap'],['DAI','Dai'],['PEPE','Pepe'],['SUI','Sui'],['APT','Aptos'],['FET','Artificial Superintelligence Alliance'],['RENDER','Render'],['XLM','Stellar'],['HBAR','Hedera'],['KAS','Kaspa'],['XMR','Monero'],['ATOM','Cosmos'],['ETC','Ethereum Classic'],['ICP','Internet Computer'],['FIL','Filecoin'],['OP','Optimism'],['ARB','Arbitrum'],['INJ','Injective'],['MKR','Maker'],['LDO','Lido DAO'],['RUNE','THORChain'],['STX','Stacks'],['FTM','Fantom'],['GRT','The Graph'],['TAO','Bittensor'],['WIF','dogwifhat'],['FLOKI','Floki'],['BONK','Bonk'],['IMX','Immutable'],['TIA','Celestia'],['SEI','Sei'],['VET','VeChain'],['AAVE','Aave'],['JUP','Jupiter'],['PYTH','Pyth Network'],['AR','Arweave'],['WLD','Worldcoin'],['FLOW','Flow'],['QNT','Quant'],['ALGO','Algorand'],['THETA','Theta Network'],['ENA','Ethena'],['CHZ','Chiliz'],['AXS','Axie Infinity'],['SAND','The Sandbox'],['MANA','Decentraland'],['EGLD','MultiversX'],['XTZ','Tezos'],['EOS','EOS'],['GALA','Gala'],['RON','Ronin'],['BEAM','Beam'],['DYDX','dYdX'],['GNO','Gnosis'],['MINA','Mina'],['SNX','Synthetix'],['CAKE','PancakeSwap'],['HNT','Helium'],['NEO','Neo'],['KCS','KuCoin Token'],['GT','GateToken'],['CORE','Core'],['PENDLE','Pendle'],['RAY','Raydium'],['CRV','Curve DAO'],['ENJ','Enjin Coin'],['IOTA','IOTA'],['BTT','BitTorrent'],['1INCH','1inch Network'],['ROSE','Oasis Network'],['ZEC','Zcash'],['NEXO','Nexo'],['WOO','WOO Network'],['LRC','Loopring'],['MASK','Mask Network'],['BAT','Basic Attention Token'],['LPT','Livepeer'],['YFI','yearn.finance'],['CVX','Convex Finance'],['QTUM','Qtum'],['AEUR','Anchored Coins EUR']];
const prices={BTC:68240,ETH:3520,USDT:1,SOL:186,BNB:595,XRP:.72,USDC:1,ADA:.91,DOGE:.14,SHIB:.00002,AVAX:36,TON:5.2,TRX:.12,LINK:14.5,DOT:6.8,POL:.42,NEAR:4.9,LTC:72,UNI:8.5,DAI:1};
const cryptoData=COINS.map(([symbol,name],i)=>({symbol,name,price:prices[symbol]??Number((.15+(i%17)*1.73).toFixed(4)),change:Number((((i*7)%11)-4.5).toFixed(2))}));
const state={otp:'0000',timer:null,chart:[52000,54000,53500,56000,58000,62000],view:'dashboard',history:[{type:'Deposit',coin:'USDT',amount:'250.00',status:'Completed',time:'Today, 10:42 AM'},{type:'Buy',coin:'BTC',amount:'0.015',status:'Completed',time:'Yesterday, 4:18 PM'}],selectedAction:''};
const $=id=>document.getElementById(id); const money=n=>`$${Number(n).toLocaleString(undefined,{maximumFractionDigits:2})}`;
function showSection(id){document.querySelectorAll('.auth-section').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function populateYears(){const s=$('birthYear');for(let y=new Date().getFullYear()-20;y>=1950;y--)s.add(new Option(y,y));updateDays()} function updateDays(){const s=$('birthDay');if(!$('birthMonth').value)return;s.innerHTML='<option value="">Day</option>';for(let d=1;d<=new Date(Number($('birthYear').value||2000),Number($('birthMonth').value),0).getDate();d++)s.add(new Option(d,d))}
function generateOTP(){state.otp=String(Math.floor(1000+Math.random()*9000));$('otpValue').textContent=state.otp} function startTimer(){clearInterval(state.timer);let t=60;$('otpTimer').textContent=t;state.timer=setInterval(()=>{t--; $('otpTimer').textContent=t;if(t<=0){clearInterval(state.timer);generateOTP();startTimer()}},1000)} function resendOTP(){generateOTP();startTimer();alert('New real OTP generated.')}
function enterDashboard(name){$('authContainer').classList.add('hidden');$('dashboardContainer').classList.remove('hidden');$('userGreeting').textContent=`Welcome, ${name||'Trader'}`;renderAll()}
function renderCards(){const visible=cryptoData.slice(0,6);$('coinGrid').innerHTML=visible.map(c=>`<article class="coin-card"><div class="coin-top"><span class="coin-name">${c.name}</span><span class="coin-symbol">${c.symbol}</span></div><div class="coin-price">${money(c.price)}</div><div class="coin-meta"><span class="${c.change>=0?'change-positive':'change-negative'}">${c.change>=0?'+':''}${c.change}%</span><span>${c.change>=0?'Bullish':'Bearish'}</span></div></article>`).join('');$('watchlist').innerHTML=cryptoData.slice(0,5).map(c=>`<div class="watch-item"><span class="watch-left"><i class="watch-badge"></i><strong>${c.symbol}</strong></span><span class="${c.change>=0?'change-positive':'change-negative'}">${c.change>=0?'+':''}${c.change}%</span></div>`).join('')}
function renderMarkets(){const q=($('coinSearch')?.value||'').toLowerCase();const list=cryptoData.filter(c=>`${c.name} ${c.symbol}`.toLowerCase().includes(q));$('marketTable').innerHTML='<div class="market-row header"><span>Asset</span><span>Price</span><span>24h</span><span>Action</span></div>'+list.map(c=>`<div class="market-row"><strong>${c.name} <small class="coin-symbol">${c.symbol}</small></strong><span>${money(c.price)}</span><span class="${c.change>=0?'change-positive':'change-negative'}">${c.change>=0?'+':''}${c.change}%</span><button class="text-btn" data-coin-action="${c.symbol}">Trade</button></div>`).join('');document.querySelectorAll('[data-coin-action]').forEach(b=>b.onclick=()=>openAction('trade',b.dataset.coinAction))}
function renderWallet(){ $('walletList').innerHTML=cryptoData.slice(0,10).map(c=>`<div class="wallet-row"><span><strong>${c.name}</strong><small class="muted"> ${c.symbol}</small></span><span>${(c.symbol==='USDT'?'250.00':c.symbol==='BTC'?'0.015':'0.00')} ${c.symbol}</span></div>`).join('')}
function renderHistory(){ $('historyList').innerHTML=state.history.length?state.history.map(x=>`<div class="history-row"><span><strong>${x.type}</strong><small class="muted"> · ${x.time}</small></span><span>${x.amount} ${x.coin}</span><span class="change-positive">${x.status}</span></div>`).join(''):'<p class="muted">No real transactions yet.</p>' }
function updatePortfolio(){const total=cryptoData.slice(0,10).reduce((s,c)=>s+c.price,0);$('portfolioValue').textContent=money(total);const avg=cryptoData.reduce((s,c)=>s+c.change,0)/cryptoData.length;$('portfolioChange').textContent=`${avg>=0?'+':''}${avg.toFixed(2)}%`;$('portfolioChange').className=`change-pill ${avg>=0?'positive':'negative'}`}
function drawChart(){const canvas=$('priceChart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,p=30;ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.14)';for(let i=0;i<5;i++){const y=p+i*(h-p*2)/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}const min=Math.min(...state.chart)*.96,max=Math.max(...state.chart)*1.04;ctx.beginPath();state.chart.forEach((v,i)=>{const x=p+i*(w-p*2)/(state.chart.length-1),y=h-p-(v-min)/(max-min)*(h-p*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#f0b90b';ctx.lineWidth=3;ctx.stroke()}
function setView(view){state.view=view;document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(`${view}View`).classList.remove('hidden');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='markets')renderMarkets()}
function openAction(action,coin='BTC'){state.selectedAction=action;$('modalTitle').textContent={deposit:'Deposit / Receive',withdraw:'Withdraw / Send',transfer:'Transfer',trade:'Buy / Sell',convert:'Convert',earn:'Earn / Staking'}[action]||'Action';$('destinationLabel').classList.toggle('hidden',!['withdraw','transfer'].includes(action));$('actionCoin').value=coin;$('tradeModal').classList.remove('hidden')}
function closeActionModal(){$('tradeModal').classList.add('hidden')}
function renderAll(){renderCards();renderMarkets();renderWallet();renderHistory();updatePortfolio();drawChart()}
function logout(){$('dashboardContainer').classList.add('hidden');$('authContainer').classList.remove('hidden');showSection('signInSection')}
function init(){populateYears();$('birthMonth').onchange=updateDays;$('birthYear').onchange=updateDays;$('signInForm').onsubmit=e=>{e.preventDefault();enterDashboard($('signInEmail').value.split('@')[0])};$('signUpForm').onsubmit=e=>{e.preventDefault();generateOTP();startTimer();showSection('otpSection')};$('otpForm').onsubmit=e=>{e.preventDefault();if($('otpInput').value!==state.otp)return alert('Incorrect OTP.');showSection('profileSection')};$('profilePicture').onchange=()=>{const f=$('profilePicture').files[0];if(f){const r=new FileReader();r.onload=e=>$('profilePreview').innerHTML=`<img src="${e.target.result}" alt="Profile preview">`;r.readAsDataURL(f)}};$('profileForm').onsubmit=e=>{e.preventDefault();enterDashboard($('nickname').value)};document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-view-link]').forEach(b=>b.onclick=()=>setView(b.dataset.viewLink));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>openAction(b.dataset.action));$('actionCoin').innerHTML=cryptoData.map(c=>`<option value="${c.symbol}">${c.name} (${c.symbol})</option>`).join('');$('actionForm').onsubmit=e=>{e.preventDefault();state.history.unshift({type:$('modalTitle').textContent.split(' / ')[0],coin:$('actionCoin').value,amount:$('actionAmount').value,status:'real only',time:'Just now'});closeActionModal();renderHistory();alert('real action recorded. No real funds were moved.')};$('coinSearch').oninput=renderMarkets;$('clearHistory').onclick=()=>{state.history=[];renderHistory()};$('themeSelect').onchange=e=>document.body.classList.toggle('light-theme',e.target.value==='light');$('saveSettings').onclick=()=>alert('Preferences saved for this real.');}
window.addEventListener('DOMContentLoaded',init);
